#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# MY CUSTOM CONFIGURATIONS

# path
path+=('/home/ndlr/bin')
path+=('/home/ndlr/.config/emacs/bin')
path+=('/home/ndlr/.local/bin')
#path+=('/home/minjiu/.local/share/gem/ruby/3.0.0/bin')
export PATH

export EDITOR=nvim
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#354f52,underline"

# mapping
bindkey "^[OH" beginning-of-line
bindkey "^[OF" end-of-line

alias sudo='doas'

# power
alias performance='powerprofilesctl set performance'
alias balanced='powerprofilesctl set balanced'
alias saver='powerprofilesctl set power-saver'

# sudo root GUI apps
alias addroot='xhost si:localuser:root'

# test photo
alias prepcam="sudo modprobe v4l2loopback && pkill gphoto"
alias dslrcam="gphoto2 --stdout autofocusdrive=1 --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video4"

# paru
alias parU='paru -Sua'
alias parQ='paru -Qua'

# ssh
#alias ssh='TERM=xterm-256color $(which ssh)'


# other
alias v='nvim'
alias vkick='NVIM_APPNAME=vkick nvim'
#alias fastfetch='fastfetch -c ~/.config/fastfetch/config.jsonc'
alias e='emacsclient -t'
alias remacs='kill $(pidof emacs); emacs --daemon'
# vpn
alias conn='ipvanish connect --country SG'
alias myip='curl ipinfo.io/json'
alias kvpn='sudo pkill -u root openvpn'
alias swn='focus --sound tick_tock'

# ls exa
# general use
alias ls='exa -l --group-directories-first'                                                         # ls
alias l='exa -lbF --git'                                               # list, size, type, git
alias ll='exa -lbGF --git'                                             # long list
alias llm='exa -lbGF --git --sort=modified'                            # long list, modified date sort
alias la='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'  # all list
alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale' # all + extended list

# speciality views
alias lS='exa -1'                                                      # one column, just names
#alias lt='exa --tree --level=2'                                        # tree

# vagrant
export VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1
export IMG='/run/media/ndlr/data1/img/'
export WINIT_HIDPI_FACTOR=3
test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)
export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORMTHEME="qt5ct"
# export FZF_DEFAULT_OPTS='--color=bg+:#293739,bg:#1B1D1E,border:#808080,spinner:#E6DB74,hl:#7E8E91,fg:#F8F8F2,header:#7E8E91,info:#A6E22E,pointer:#A6E22E,marker:#F92672,fg+:#F8F8F2,prompt:#F92672,hl+:#F92672'
export ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache/zsh}"

alias vscr='NVIM_APPNAME=vscr nvim'
alias uvr='python manage.py'

export GOPATH=$HOME/Projects/go
# FZF Plugin
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS
--color=fg:#767777,bg:#1b1c1d,hl:#bbc7b1,gutter:#1b1c1d
--color=fg+:#748fa6,bg+:#222324,hl+:#bbc7b1
--color=info:#a69e6f,prompt:#bbc7b1,pointer:#748fa6
--color=marker:#72966c,spinner:#72966c,header:#72966c"
autoload -Uz promptinit
promptinit
prompt pure
